- name: check the facts
  hosts: local
  connection: local
  tasks:
  - name: install nginx if redhat
  andansible.builtin.dnf:
    name: nginx
    state: latest
  when: ansible_os_family == "RedHat" # use ansible-while refering the factss