# Functions: Taking i/p and providing the o/p, execute whenver we call
# functions == filter, We can write fuctions but we need to write python code, we can use default in built functions from ansible

- name: fuctions
  hosts: local
  connection: local
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Ramesh') }}"